# -*- fill-column: 76; -*-
#+TITLE: XDP 编程实战教程
#+OPTIONS: ^:nil

本仓库包含一个教程，旨在向你介绍有效编写 Linux 内核中 eXpress Data Path
（XDP）系统程序所需的基本步骤。XDP 提供与内核集成的高性能可编程数据包处理
能力。

本教程由多个课程组成，每个课程都有自己的目录。请从 "basicXX" 开头的课程
开始，并阅读每个目录中的 README.org 文件以获取该课程的说明。

继续阅读下文以了解 XDP 简介和本教程的概述，或者直接跳转到
[[file:basic01-xdp-pass/README.org][第一课]]。

* 目录                                                                  :TOC:
- [[#简介][简介]]
- [[#第一步-安装依赖][第一步：安装依赖]]
- [[#课程组织方式][课程组织方式]]
  - [[#基础设置课程][基础设置课程]]
  - [[#数据包处理课程][数据包处理课程]]
  - [[#高级课程][高级课程]]

* 简介

XDP 是上游 Linux 内核的一部分，使用户能够将数据包处理程序安装到内核中，
这些程序将在内核对数据进行任何其他处理之前，针对每个到达的数据包执行。
程序使用受限的 C 语言编写，并编译成 eBPF 字节码格式，在经过安全验证后
在内核中执行并进行 JIT 编译。这种方法提供了极大的灵活性和高性能，并能
很好地与系统的其他部分集成。有关 XDP 的一般介绍，请阅读
[[https://github.com/xdp-project/xdp-paper/blob/master/xdp-the-express-data-path.pdf][学术论文 (pdf)]] 或 [[https://cilium.readthedocs.io/en/latest/bpf/][Cilium BPF 参考指南]]。

本教程旨在提供使用 XDP 系统成功编写有用程序所需不同步骤的实践介绍。
我们假设你对 Linux 网络以及如何使用 =iproute2= 工具套件进行配置有基本
了解，但不假设你有 eBPF 或 XDP 的先前经验。编程经验也很有帮助：课程全部
使用 C 语言编写，包括一些基本的指针运算和别名操作。

本教程是一项正在进行的工作，最初是为 2019 年 3 月在布拉格举行的
[[https://www.netdevconf.org/0x13/session.html?tutorial-XDP-hands-on][Netdev 会议]] 上作为现场教程使用而创建的。由于内核 BPF 子系统继续快速
发展，本教程并未跟上所有的发展。但是，这里展示的所有内容都可以在最新
内核上运行，本教程作为一个独立的入门介绍，任何人都可以通过学习来掌握
XDP 基础知识。非常欢迎为实现这一目标提供意见和贡献；只需在
[[https://github.com/xdp-project/xdp-tutorial/][Github 仓库]] 中开启 issue 或提交 pull request。

* 第一步：安装依赖

在开始完成本教程的步骤之前，你需要在系统上安装一些依赖项。这些在
[[file:setup_dependencies.org]] 中有描述。

我们还提供了一个辅助脚本，它将为你设置一个带有虚拟接口的测试环境，
供你测试代码。这在基础课程中有介绍，也有 [[file:testenv/README.org][它自己的 README 文件]]。

* 课程组织方式

本教程分为多个课程；每个课程都有自己的子目录，课程按类别分组：

- 基础设置（以 basicXX 开头的目录）
- 数据包处理（以 packetXX 开头的目录）
- 高级主题（以 advancedXX 开头的目录）

我们建议你从 "basic" 课程开始，并按数字顺序学习每个类别中的课程。
阅读每个课程目录中的 README.org 文件以获取完成课程的说明。

** 基础设置课程

我们建议你从这些课程开始，因为它们将教你如何编译和检查将实现数据包
处理代码的 eBPF 程序、如何将它们加载到内核中，以及如何在之后检查状态。
作为基础课程的一部分，你还将编写一个 eBPF 程序加载器，在后续课程中会用到。

** 数据包处理课程

一旦你掌握了基础知识并知道如何将程序加载到内核中，你就可以开始处理
一些数据包了。数据包处理类别中的课程将教你处理数据包所需的不同步骤，
包括解析、重写、指示内核在处理后如何处理数据包，以及如何使用辅助函数
访问现有的内核功能。

** 高级课程

完成基础和数据包处理类别中的课程后，你应该已经准备好编写你的第一个
真正的 XDP 程序，它将对进入系统的数据包进行有用的处理。但是，当你开始
扩展程序以执行更多操作时，有一些稍微高级的主题可能会很有用。

高级课程涵盖的主题包括如何使内核其他部分的 eBPF 程序与你的 XDP 程序
交互、在程序之间传递元数据、与用户空间和内核功能交互的最佳实践，以及
如何在单个接口上运行多个 XDP 程序。
